### ISSUE TITLE
__live requests done from a page are not refreshing on a resulting route page.

### ISSUE THREAD

**Issue by opicciotto** [convertigo/c8osdk-angular-caf#3]
If on page A we execute a __live Query on an FS database view, and that this results to switch to Page B, thanks to a navigation route,  when the database is modified and the __live query is re-executed, the Page B view listening on this query is not refreshed.

Logs show that __live query is re-executed correctly, but page B is just not refreshed...

**Comment by CharlesGrimont** [comment]
Done in version 1.0.97
